---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: create {{ doc_root }} directory
  sudo: yes
  file: path={{ doc_root }} state=directory

- name: Change default nginx site
  sudo: yes
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx
